### ISSUE TITLE
Background image is not loading 

### ISSUE THREAD

**Issue by pranjalg13** [pranjalg13/fake-news-detection#14]
![cap](https://user-images.githubusercontent.com/47600057/137912377-d1a3871f-e262-49a0-93db-4bf2e64520a8.JPG)

See the image. The image should appear in the background. The image is in styles folder names pic.jpg

**Comment by vasav-prashar** [comment]
i like to work on this pls assign me

**Comment by pranjalg13** [comment]
I think you can try to install tenserflow through official website. They might have removed cli support for that version. Try installing through official tenserflow website with same version as in requirements.txt

**Comment by vasav-prashar** [comment]
Ok thanks i will try

**Comment by vasav-prashar** [comment]
https://github.com/pranjalg13/fake-news-detection/pull/16 
pls review

**Comment by pranjalg13** [comment]
Minor changes were there, but it is fixed. Nice work
